# Generated by Django 3.2.9 on 2021-12-27 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
        ('posts', '0002_auto_20211201_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='group',
            field=models.ForeignKey(blank=True, db_column='group', null=True, on_delete=django.db.models.deletion.CASCADE, to='groups.group'),
        ),
    ]
