# Generated by Django 3.0.14 on 2021-11-09 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hobbies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hobby_title', models.CharField(max_length=80)),
                ('hobby_description', models.CharField(max_length=80)),
                ('number_of_members', models.IntegerField()),
            ],
        ),
    ]
