# Generated by Django 3.2.9 on 2021-11-12 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hobbies', '0002_alter_hobbies_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hobbies',
            name='hobby_description',
            field=models.CharField(max_length=10000),
        ),
    ]
