# Generated by Django 3.2.9 on 2021-12-28 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20211228_0010'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='image',
            new_name='img',
        ),
    ]
