# Generated by Django 3.2.9 on 2021-11-28 20:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hobbies', '0005_rename_hobby_group_hobbies_hobby_category'),
        ('users', '0003_auto_20211110_1912'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Hobby',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_hobbyTitle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hobbies.hobbies')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
