# Generated by Django 3.2.9 on 2021-12-08 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hobbies', '0005_rename_hobby_group_hobbies_hobby_category'),
        ('users', '0004_user_hobby'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_accessed_hobby',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hobbies.hobbies'),
        ),
    ]
