# Generated by Django 3.2.9 on 2021-12-25 22:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
        ('hobbies', '0005_rename_hobby_group_hobbies_hobby_category'),
        ('users', '0005_user_last_accessed_hobby'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_accessed_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='groups.group'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_accessed_hobby',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hobbies.hobbies'),
        ),
        migrations.CreateModel(
            name='User_Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_groupTitle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='groups.group')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
