# Generated by Django 3.2.9 on 2022-01-11 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_auto_20211227_1442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='link',
        ),
        migrations.AddField(
            model_name='video',
            name='file',
            field=models.FileField(default=False, max_length=200, upload_to='videos'),
            preserve_default=False,
        ),
    ]
