# Generated by Django 3.2.9 on 2022-02-01 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hobbies', '0005_rename_hobby_group_hobbies_hobby_category'),
        ('notification', '0005_alter_notification_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='is_seen',
        ),
        migrations.AddField(
            model_name='notification',
            name='hobby',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hobbies.hobbies'),
        ),
    ]
