# Generated by Django 3.2.9 on 2021-12-28 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_group_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='img',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
